---
title: "Lead Inequity"
author: "Peter Menzies"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(skimr)
library(dplyr)
```

### Read in names 

```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";") %>% 
  clean_names %>% 
  # mutate(new_col = col_a / col_b * 100)
  mutate(prop_white = white / total_pop * 100) %>% 
  mutate(pct_elevated = str_replace(
    pct_elevated, pattern = ",", replace = ".")) %>%
  mutate(pct_elevated = as.numeric(pct_elevated))
```

### Explore data

```{r}
dim(stl_lead)
names(stl_lead)
```

### Create a scatterplot

```{r}
stl_lead_plot <- ggplot(data = stl_lead, aes(x = prop_white, y = pct_elevated)) +
  geom_point(size = 3, alpha = 0.5, color = "blue") +
  labs(x = "Proportion white", y = "Perecent elevated lead levels")
  
stl_lead_plot
```

#### This figure shows a negative correlation between the percent of elevated lead levels and the proportion of white children in areas of St. Louis, MO.

### Save .png to `figs` with dimensions 6 X 5

```{r}
ggsave(here::here("figs", "stl_lead_plot.jpg"), plot = stl_lead_plot,
       width = 6,
       height = 5)
```

### Create a histogram of `pct_elevated`

```{r}
pct_elevated_hist <- ggplot(data = stl_lead, aes(x = pct_elevated)) + 
  geom_histogram(fill = "cyan", color = "orange", size = 2) +
  labs(x = "Percent elevated lead levels")

pct_elevated_hist
```
### Save to `figs` as jpg

```{r}
ggsave(here::here("figs", "pct_elevated_hist.jpg"), plot = pct_elevated_hist,
       width = 6,
       height = 5)
```



